<?php
require_once __DIR__ . '/../database/config.php';
require_login();

$dateFrom=$_GET['from']??date('Y-m-d',strtotime('-6 days')); $dateTo=$_GET['to']??date('Y-m-d');
if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$dateFrom))$dateFrom=date('Y-m-d',strtotime('-6 days'));
if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$dateTo))$dateTo=date('Y-m-d');
if($dateFrom>$dateTo)[$dateFrom,$dateTo]=[$dateTo,$dateFrom];
$start=$dateFrom.' 00:00:00'; $end=$dateTo.' 23:59:59'; $p=[$start,$end];

function a_count(PDO $pdo,string $sql,array $p=[]):int{$s=$pdo->prepare($sql);$s->execute($p);return(int)$s->fetchColumn();}
$total=a_count($pdo,"SELECT COUNT(*) FROM entry_logs WHERE time_in BETWEEN ? AND ?",$p);
$granted=a_count($pdo,"SELECT COUNT(*) FROM entry_logs WHERE time_in BETWEEN ? AND ? AND status='Match'",$p);
$denied=a_count($pdo,"SELECT COUNT(*) FROM entry_logs WHERE time_in BETWEEN ? AND ? AND status='Denied'",$p);
$unique=a_count($pdo,"SELECT COUNT(DISTINCT student_id) FROM entry_logs WHERE time_in BETWEEN ? AND ? AND status='Match' AND student_id IS NOT NULL",$p);
$active=a_count($pdo,"SELECT COUNT(*) FROM students WHERE status='Active'");
$sms=a_count($pdo,"SELECT COUNT(*) FROM sms_logs WHERE sent_at BETWEEN ? AND ? AND status='Match'",$p);
$successRate=$total?round($granted/$total*100,1):0; $deniedRate=$total?round($denied/$total*100,1):0; $days=max(1,(int)((strtotime($dateTo)-strtotime($dateFrom))/86400)+1); $avgDaily=round($total/$days,1); $scansPerStudent=$unique?round($granted/$unique,1):0;

$stmt=$pdo->prepare("SELECT DATE(time_in) day,COUNT(*) total,SUM(status='Match') granted,SUM(status='Denied') denied FROM entry_logs WHERE time_in BETWEEN ? AND ? GROUP BY DATE(time_in) ORDER BY day");$stmt->execute($p);$rows=$stmt->fetchAll();$map=[];foreach($rows as $r)$map[$r['day']]=$r;
$daily=[];$period=new DatePeriod(new DateTime($dateFrom),new DateInterval('P1D'),(new DateTime($dateTo))->modify('+1 day'));foreach($period as $dt){$d=$dt->format('Y-m-d');$daily[]=['label'=>$dt->format('M j'),'total'=>(int)($map[$d]['total']??0),'granted'=>(int)($map[$d]['granted']??0),'denied'=>(int)($map[$d]['denied']??0)];}
$peakDay='-';$peakDayCount=0;foreach($map as $d=>$r)if((int)$r['total']>$peakDayCount){$peakDayCount=(int)$r['total'];$peakDay=date('M j, Y',strtotime($d));}

$stmt=$pdo->prepare("SELECT HOUR(time_in) h,COUNT(*) total FROM entry_logs WHERE time_in BETWEEN ? AND ? AND status='Match' GROUP BY HOUR(time_in) ORDER BY h");$stmt->execute($p);$hourMap=[];foreach($stmt->fetchAll() as $r)$hourMap[(int)$r['h']]=(int)$r['total'];
$stmt=$pdo->prepare("SELECT HOUR(time_in) h,COUNT(*) total FROM entry_logs WHERE time_in BETWEEN ? AND ? AND status='Match' AND transaction_type='Entry' GROUP BY HOUR(time_in) ORDER BY h");$stmt->execute($p);$entryHourMap=[];foreach($stmt->fetchAll() as $r)$entryHourMap[(int)$r['h']]=(int)$r['total'];
$stmt=$pdo->prepare("SELECT HOUR(time_in) h,COUNT(*) total FROM entry_logs WHERE time_in BETWEEN ? AND ? AND status='Match' AND transaction_type='Exit' GROUP BY HOUR(time_in) ORDER BY h");$stmt->execute($p);$exitHourMap=[];foreach($stmt->fetchAll() as $r)$exitHourMap[(int)$r['h']]=(int)$r['total'];
$hourLabels=[];$hourData=[];$entryHourData=[];$exitHourData=[];for($h=0;$h<24;$h++){ $hourLabels[]=date('g A',mktime($h,0,0));$hourData[]=$hourMap[$h]??0;$entryHourData[]=$entryHourMap[$h]??0;$exitHourData[]=$exitHourMap[$h]??0;}
$peakHour='-';$peakHourCount=0;foreach($hourMap as $h=>$n)if($n>$peakHourCount){$peakHourCount=$n;$peakHour=date('g A',mktime($h,0,0));}
$peakEntryHour='-';$peakEntryCount=0;foreach($entryHourMap as $h=>$n)if($n>$peakEntryCount){$peakEntryCount=$n;$peakEntryHour=date('g A',mktime($h,0,0));}
$peakExitHour='-';$peakExitCount=0;foreach($exitHourMap as $h=>$n)if($n>$peakExitCount){$peakExitCount=$n;$peakExitHour=date('g A',mktime($h,0,0));}

$stmt=$pdo->prepare("SELECT grade,COUNT(*) total FROM entry_logs WHERE time_in BETWEEN ? AND ? AND status='Match' AND grade IS NOT NULL GROUP BY grade ORDER BY total DESC,grade");$stmt->execute($p);$gradeRows=$stmt->fetchAll();
$stmt=$pdo->prepare("SELECT COALESCE(reason,'Unspecified') reason,COUNT(*) total FROM entry_logs WHERE time_in BETWEEN ? AND ? AND status='Denied' GROUP BY reason ORDER BY total DESC,reason LIMIT 8");$stmt->execute($p);$denialRows=$stmt->fetchAll();
$stmt=$pdo->prepare("SELECT verification_method,COUNT(*) total FROM entry_logs WHERE time_in BETWEEN ? AND ? AND status='Match' GROUP BY verification_method ORDER BY total DESC");$stmt->execute($p);$methods=$stmt->fetchAll();
$stmt=$pdo->prepare("SELECT transaction_type,COUNT(*) total FROM entry_logs WHERE time_in BETWEEN ? AND ? AND status='Match' GROUP BY transaction_type");$stmt->execute($p);$types=$stmt->fetchAll();$typeMap=['Entry'=>0,'Exit'=>0];foreach($types as $r)$typeMap[$r['transaction_type']]=(int)$r['total'];
$stmt=$pdo->prepare("SELECT COALESCE(NULLIF(grade,''),'Unspecified') grade,COUNT(*) total FROM students WHERE status='Active' GROUP BY grade ORDER BY total DESC,grade");$stmt->execute();$studentGrades=$stmt->fetchAll();
$stmt=$pdo->prepare("SELECT student_id,COALESCE(MAX(fullname),'Unknown') fullname,MAX(grade) grade,COUNT(*) total FROM entry_logs WHERE time_in BETWEEN ? AND ? AND status='Match' AND student_id IS NOT NULL GROUP BY student_id ORDER BY total DESC,fullname LIMIT 8");$stmt->execute($p);$topStudents=$stmt->fetchAll();

$pageTitle='Analytics';$pageHeading='Analytics';$pageSubheading='Campus entry performance, trends, and operational insights';$activePage='analytics';require_once __DIR__.'/../includes/header.php';require_once __DIR__.'/../includes/sidebar.php';
?>
<div class="sg-content"><?php require_once __DIR__.'/../includes/navbar.php'; ?><main class="sg-main sg-analytics-page">
<div class="sg-card mb-3 sg-no-print"><form method="GET" class="row g-3 align-items-end"><div class="col-sm-6 col-lg-3"><label class="form-label">From Date</label><div class="sg-date-field"><input type="date" name="from" value="<?=e($dateFrom)?>" class="form-control"></div></div><div class="col-sm-6 col-lg-3"><label class="form-label">End Date</label><div class="sg-date-field"><input type="date" name="to" value="<?=e($dateTo)?>" class="form-control"></div></div><div class="col-sm-6 col-lg-2"><button class="btn btn-sg-primary w-100" type="submit"><i class="bi bi-arrow-repeat me-1"></i>Refresh Analytics</button></div></form></div>

<div class="row g-3 mb-3">
<?php $kpis=[['Total Scans',$total,'bi-activity','blue'],['Granted',$granted,'bi-check-circle-fill','green'],['Denied',$denied,'bi-shield-x','red'],['Unique Students',$unique,'bi-people-fill','purple'],['Grant Rate',$successRate.'%','bi-percent','green'],['Denied Rate',$deniedRate.'%','bi-graph-down-arrow','red'],['Avg / Day',$avgDaily,'bi-calendar2-week','blue'],['Scans / Student',$scansPerStudent,'bi-person-check','purple']];foreach($kpis as $k):?><div class="col-6 col-md-4 col-xl"><div class="sg-card sg-analytics-kpi"><div class="icon-box bg-icon-<?=$k[3]?>"><i class="bi <?=$k[2]?>"></i></div><div><div class="stat-value"><?=e((string)$k[1])?></div><div class="stat-label"><?=e($k[0])?></div></div></div></div><?php endforeach; ?>
</div>

<div class="row g-3 mb-3"><div class="col-lg-8"><div class="sg-card"><div class="sg-card-heading"><h2><i class="bi bi-graph-up"></i> Daily Activity Trend</h2><span class="sg-report-note">Peak day: <?=e($peakDay)?></span></div><div class="sg-analytics-chart-wrap sg-analytics-chart-tall"><canvas id="dailyAnalyticsChart"></canvas></div></div></div><div class="col-lg-4"><div class="sg-card h-100"><div class="sg-card-heading"><h2><i class="bi bi-pie-chart-fill"></i> Verification Methods</h2></div><div class="sg-analytics-donut-wrap"><canvas id="methodAnalyticsChart"></canvas></div></div></div></div>
<div class="row g-3 mb-3"><div class="col-lg-7"><div class="sg-card"><div class="sg-card-heading"><h2><i class="bi bi-clock-history"></i> Activity by Hour</h2></div><div class="sg-peak-hour-strip"><div><span>Peak Granted</span><strong><?=e($peakHour)?></strong><small><?=number_format($peakHourCount)?> scans</small></div><div><span>Peak Entry</span><strong><?=e($peakEntryHour)?></strong><small><?=number_format($peakEntryCount)?> entries</small></div><div><span>Peak Exit</span><strong><?=e($peakExitHour)?></strong><small><?=number_format($peakExitCount)?> exits</small></div></div><div class="sg-analytics-chart-wrap"><canvas id="hourAnalyticsChart"></canvas></div></div></div><div class="col-lg-5"><div class="sg-card"><div class="sg-card-heading"><h2><i class="bi bi-arrow-left-right"></i> Entry vs Exit</h2></div><div class="sg-analytics-donut-wrap"><canvas id="typeAnalyticsChart"></canvas></div></div></div></div>
<div class="row g-3 mb-3"><div class="col-lg-6"><div class="sg-card h-100"><div class="sg-card-heading"><h2><i class="bi bi-mortarboard"></i> Activity by Grade</h2></div><div class="table-responsive"><table class="table sg-report-table"><thead><tr><th>Grade</th><th class="text-end">Transactions</th><th class="text-end">Share</th></tr></thead><tbody><?php foreach($gradeRows as $r):$share=$granted?round($r['total']/$granted*100,1):0;?><tr><td><?=e($r['grade'])?></td><td class="text-end"><?=number_format($r['total'])?></td><td class="text-end"><?=$share?>%</td></tr><?php endforeach;if(!$gradeRows):?><tr><td colspan="3" class="text-center text-muted">No grade-level activity.</td></tr><?php endif;?></tbody></table></div></div></div><div class="col-lg-6"><div class="sg-card h-100"><div class="sg-card-heading"><h2><i class="bi bi-exclamation-triangle"></i> Denial Reasons</h2></div><div class="table-responsive"><table class="table sg-report-table"><thead><tr><th>Reason</th><th class="text-end">Count</th></tr></thead><tbody><?php foreach($denialRows as $r):?><tr><td><?=e($r['reason'])?></td><td class="text-end fw-bold"><?=number_format($r['total'])?></td></tr><?php endforeach;if(!$denialRows):?><tr><td colspan="2" class="text-center text-muted">No denied transactions.</td></tr><?php endif;?></tbody></table></div></div></div></div>
<div class="row g-3"><div class="col-lg-6"><div class="sg-card h-100"><div class="sg-card-heading"><h2><i class="bi bi-person-lines-fill"></i> Most Active Students</h2></div><div class="table-responsive"><table class="table sg-report-table"><thead><tr><th>Student</th><th>Grade</th><th class="text-end">Scans</th></tr></thead><tbody><?php foreach($topStudents as $r):?><tr><td><?=e($r['fullname'])?><div class="small text-muted"><?=e($r['student_id'])?></div></td><td><?=e($r['grade']?:'—')?></td><td class="text-end fw-bold"><?=number_format($r['total'])?></td></tr><?php endforeach;if(!$topStudents):?><tr><td colspan="3" class="text-center text-muted">No student activity.</td></tr><?php endif;?></tbody></table></div></div></div><div class="col-lg-6"><div class="sg-card h-100"><div class="sg-card-heading"><h2><i class="bi bi-database-check"></i> Operational Snapshot</h2></div><div class="sg-analytics-insights"><div><span>Active students</span><strong><?=number_format($active)?></strong></div><div><span>SMS sent</span><strong><?=number_format($sms)?></strong></div><div><span>Peak day volume</span><strong><?=number_format($peakDayCount)?></strong></div><div><span>Peak hour volume</span><strong><?=number_format($peakHourCount)?></strong></div></div><div class="small text-muted mt-3">Analytics is calculated directly from entry logs and related system records for the selected period.</div></div></div></div>
</main></div>
<script>document.addEventListener('DOMContentLoaded',()=>{if(typeof Chart==='undefined')return;const light=document.documentElement.getAttribute('data-theme')==='light',text=light?'#475569':'#b7cfda',grid=light?'rgba(71,85,105,.12)':'rgba(183,207,218,.10)';Chart.defaults.color=text;Chart.defaults.borderColor=grid;new Chart(document.getElementById('dailyAnalyticsChart'),{type:'line',data:{labels:<?=json_encode(array_column($daily,'label'))?>,datasets:[{label:'Granted',data:<?=json_encode(array_column($daily,'granted'))?>,borderColor:'#22C55E',backgroundColor:'rgba(34,197,94,.10)',fill:true,tension:.35},{label:'Denied',data:<?=json_encode(array_column($daily,'denied'))?>,borderColor:'#EF4444',backgroundColor:'rgba(239,68,68,.06)',fill:true,tension:.35}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom'}},scales:{x:{grid:{display:false}},y:{beginAtZero:true,ticks:{precision:0},grid:{color:grid}}}}});new Chart(document.getElementById('methodAnalyticsChart'),{type:'doughnut',data:{labels:<?=json_encode(array_column($methods,'verification_method')?:['No data'])?>,datasets:[{data:<?=json_encode(array_map('intval',array_column($methods,'total'))?:[1])?>,backgroundColor:['#3B82F6','#8B5CF6','#22C55E'],borderWidth:0}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom'}}}});new Chart(document.getElementById('typeAnalyticsChart'),{type:'doughnut',data:{labels:['Entry','Exit'],datasets:[{data:[<?=$typeMap['Entry']?>,<?=$typeMap['Exit']?>],backgroundColor:['#22C55E','#F59E0B'],borderWidth:0}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom'}}}});new Chart(document.getElementById('hourAnalyticsChart'),{type:'bar',data:{labels:<?=json_encode($hourLabels)?>,datasets:[{label:'Granted Scans',data:<?=json_encode($hourData)?>,backgroundColor:'#06B6D4',borderRadius:5},{label:'Entries',data:<?=json_encode($entryHourData)?>,backgroundColor:'#22C55E',borderRadius:5},{label:'Exits',data:<?=json_encode($exitHourData)?>,backgroundColor:'#F59E0B',borderRadius:5}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom'}},scales:{x:{ticks:{maxRotation:0,autoSkip:true,maxTicksLimit:12},grid:{display:false}},y:{beginAtZero:true,ticks:{precision:0},grid:{color:grid}}}}});});</script>
<?php require_once __DIR__.'/../includes/footer.php'; ?>
